version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - 'mariadb_data:/bitnami'
  matomo:
    image: 'bitnami/matomo:3'
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER}
      - MATOMO_DATABASE_USER=${MATOMO_DATABASE_USER}
      - MATOMO_DATABASE_NAME=${MATOMO_DATABASE_NAME}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DATABASE_PASSWORD}
      - MATOMO_WEBSITE_NAME=${MATOMO_WEBSITE_NAME}
      - MATOMO_WEBSITE_HOST=${MATOMO_WEBSITE_HOST}
      - MATOMO_USERNAME=${MATOMO_USERNAME}
      - MATOMO_PASSWORD=${MATOMO_PASSWORD}
      - MATOMO_EMAIL=${MATOMO_EMAIL}
      - MATOMO_ENABLE_PROXY_URI_HEADER=${MATOMO_ENABLE_PROXY_URI_HEADER}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_PORT=${SMTP_PORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - '80'
      # - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'matomo_data:/bitnami'
    networks: 
      - default
      
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local

networks: 
  default:
      external:
        name: nginx-proxy